# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

sudo: required

dist: xenial

services:
   - docker

branches:
  only:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip

install:
  - pip3 install -U setuptools
  - pip3 install -r test/requirements.txt --user

language: java
jdk: openjdk11

script: ./test/test.py

