# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

sudo: required

services:
   - docker

branches:
  only:
  - master

install: pip3 install -r test/requirements.txt --user

language: java
jdk: openjdk11

script: ./test/test.py

