# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
# Global settings
exclude:
    - test
    - open_index.json

# Site settings
title      : Vespa
email      : ""
description: ""
baseurl    : ""
url        : ""
defaults:
    -
        scope:
            path  : ""
        values:
            layout: "default"
            index : true

search:
    namespace: "open"
    endpoint : "https://vespa-documentation-search.vespa.global.vespa.oath.cloud"
    do_feed  : true
    do_index_removal_before_feed: false
    feed_endpoints:
        - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.public.vespa.oath.cloud/
          indexes:
              - open_index.json

# Build settings
markdown: kramdown
