# Global settings
exclude:
    - screwdriver.yaml
    - vespa_index.json
    - scripts

# Site settings
title: Vespa
email: ""
description: ""
baseurl: ""
url: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            index: true

# Search settings
search:
    do_feed: true
    do_index_removal_before_feed: false
    endpoint: "https://vespa-documentation-search.vespa.yahooapis.com:4443"
    feed: "vespa_index.json"
    doctype: "open"

# Build settings
markdown: kramdown

