# Global settings

# Site settings
title: Vespa
email: ""
description: ""
baseurl: ""
url: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            index: true

# Build settings
markdown: kramdown

