# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
# Global settings

# Site settings
title: Vespa
email: ""
description: ""
baseurl: ""
url: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            index: true

search:
    doctype: "open"

# Build settings
markdown: kramdown

