# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
# Global settings
exclude:
    - test

# Site settings
title: Vespa
email: ""
description: ""
baseurl: ""
url: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            index: true

search:
    doctype: "open"
    endpoint: "https://vespa-documentation-search--vespa.aws-us-east-1a.vespa.oath.cloud:4443"

plugins:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
