platform: generic

shared:
    notifications:
        email: vespa-cd@yahoo-inc.com

jobs:
    component:
        order: [install_ruby, install_jekyll, feed]
        steps:
            install_ruby:
                description: Install ruby
                command: yinst install yruby -br test
            install_jekyll:
                description: Install Jekyll and dependencies
                command: sudo gem install jekyll nokogiri
            feed:
                description: Feed to Vespa instance
                command: python ./scripts/feed_to_vespa.py

    pull-request:
        order: [noop]
        steps:
            noop:
                description: Do nothing on PRs
                command: /bin/true

