# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

endpoints:
    - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.public.vespa.oath.cloud/
      indexes:
          - ../open_index.json

do_feed: true
do_index_removal_before_feed: false
