name: Vespa Documentation Search Feed
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Build site
      run: |
        bundle install
        pwd
        bundle exec jekyll build -p search-feed/_plugins -d search-feed
        pwd

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Feed site
      env:
        DATA_PLANE_PUBLIC_KEY: ${{ secrets.DATA_PLANE_PUBLIC_KEY }}
        DATA_PLANE_PRIVATE_KEY: ${{ secrets.DATA_PLANE_PRIVATE_KEY }}
      run: |
        pip3 install PyYAML
        pwd
        cd search-feed
        pwd
        ./feed_to_vespa.py
